# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamesImagesFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post_type', models.CharField(choices=[('facebook_games', 'Facebook Games'), ('test_yourself', 'Test Yourself')], default='facebook_games', max_length=25)),
                ('image_banner', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('buzz', models.BooleanField(default=False)),
                ('age_categories', models.CharField(choices=[('default', 'Default'), ('children', 'Children'), ('young', 'Young'), ('adults', 'Adults')], default='default', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='whatsbuzz.Post')),
            ],
        ),
        migrations.CreateModel(
            name='UserNameFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_user_name', models.CharField(choices=[('empty', ''), ('first_name', 'First Name'), ('last_name', 'Last Name'), ('full_name', 'First and Last Name')], default='empty', max_length=255)),
                ('name_x', models.PositiveIntegerField()),
                ('name_y', models.PositiveIntegerField()),
                ('font_color', models.CharField(max_length=255)),
                ('font_size', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_users', to='whatsbuzz.Post')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileImageFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_x', models.PositiveIntegerField()),
                ('profile_image_y', models.PositiveIntegerField()),
                ('profile_width', models.PositiveIntegerField()),
                ('profile_height', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='whatsbuzz.Post')),
            ],
        ),
        migrations.AddField(
            model_name='gamesimagesfb',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_images', to='whatsbuzz.Post'),
        ),
    ]
