# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_he', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True)),
                ('body_he', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner_image', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('buzz', models.BooleanField(default=False)),
                ('age_categories', models.CharField(choices=[('default', 'Default'), ('children', 'Children'), ('young', 'Young'), ('adults', 'Adults')], default='default', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookGamesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_image', to='whatsbuzz.FacebookGame')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_profile_image', to='whatsbuzz.FacebookGame')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(choices=[('empty', ''), ('first_name', 'First Name'), ('last_name', 'Last Name'), ('full_name', 'First and Last Name')], default='empty', max_length=255)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=255)),
                ('font_size', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_username', to='whatsbuzz.FacebookGame')),
            ],
        ),
        migrations.CreateModel(
            name='TestYourself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_he', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True)),
                ('body_he', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner_image', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('buzz', models.BooleanField(default=False)),
                ('age_categories', models.CharField(choices=[('default', 'Default'), ('children', 'Children'), ('young', 'Young'), ('adults', 'Adults')], default='default', max_length=25)),
                ('code', models.TextField()),
                ('code_he', models.TextField(null=True)),
                ('code_en', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_he', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True)),
                ('body_he', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner_image', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('buzz', models.BooleanField(default=False)),
                ('age_categories', models.CharField(choices=[('default', 'Default'), ('children', 'Children'), ('young', 'Young'), ('adults', 'Adults')], default='default', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('email', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_time_visit', models.DateTimeField()),
            ],
        ),
    ]
