# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 10:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbuzz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookgame',
            options={'verbose_name': 'Facebook Game', 'verbose_name_plural': 'Facebook Games'},
        ),
        migrations.AlterModelOptions(
            name='facebookgamesimage',
            options={'verbose_name': 'facebook background image', 'verbose_name_plural': 'facebook background images'},
        ),
        migrations.AlterModelOptions(
            name='facebookprofileimage',
            options={'verbose_name': 'facebook profile image', 'verbose_name_plural': 'facebook profile images'},
        ),
        migrations.AlterModelOptions(
            name='facebookusername',
            options={'verbose_name': 'facebook username', 'verbose_name_plural': 'facebook usernames'},
        ),
        migrations.AlterModelOptions(
            name='testyourself',
            options={'verbose_name': 'Test Yourself', 'verbose_name_plural': 'Tests Yourself'},
        ),
        migrations.AlterModelOptions(
            name='trend',
            options={'verbose_name': 'Trend', 'verbose_name_plural': 'Trends'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Facebook User', 'verbose_name_plural': 'Facebook Users'},
        ),
        migrations.AddField(
            model_name='facebookgame',
            name='publish',
            field=models.DateTimeField(null=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='testyourself',
            name='publish',
            field=models.DateTimeField(null=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='trend',
            name='publish',
            field=models.DateTimeField(null=True, verbose_name='publish'),
        ),
        migrations.AlterField(
            model_name='facebookgame',
            name='age_categories',
            field=models.CharField(choices=[('default', 'Default'), ('children', 'Children'), ('young', 'Young'), ('adults', 'Adults')], default='default', max_length=25, verbose_name='age categories'),
        ),
        migrations.AlterField(
            model_name='facebookgame',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='facebookgame',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='facebookgame',
            name='body_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='facebookgame',
            name='body_he',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='facebookgame',
            name='buzz',
            field=models.BooleanField(default=False, verbose_name='buzz'),
        ),
        migrations.AlterField(
            model_name='facebookgame',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='facebookgame',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='facebookgame',
            name='title_he',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='facebookgamesimage',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='facebookprofileimage',
            name='height',
            field=models.PositiveIntegerField(verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='facebookprofileimage',
            name='width',
            field=models.PositiveIntegerField(verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='facebookprofileimage',
            name='x',
            field=models.PositiveIntegerField(verbose_name='x'),
        ),
        migrations.AlterField(
            model_name='facebookprofileimage',
            name='y',
            field=models.PositiveIntegerField(verbose_name='y'),
        ),
        migrations.AlterField(
            model_name='facebookusername',
            name='color',
            field=models.CharField(max_length=255, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='facebookusername',
            name='font_size',
            field=models.PositiveIntegerField(verbose_name='font_size'),
        ),
        migrations.AlterField(
            model_name='facebookusername',
            name='username',
            field=models.CharField(choices=[('empty', ''), ('first_name', 'First Name'), ('last_name', 'Last Name'), ('full_name', 'First and Last Name')], default='empty', max_length=255, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='facebookusername',
            name='x',
            field=models.PositiveIntegerField(verbose_name='x'),
        ),
        migrations.AlterField(
            model_name='facebookusername',
            name='y',
            field=models.PositiveIntegerField(verbose_name='y'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='age_categories',
            field=models.CharField(choices=[('default', 'Default'), ('children', 'Children'), ('young', 'Young'), ('adults', 'Adults')], default='default', max_length=25, verbose_name='age categories'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='body_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='body_he',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='buzz',
            field=models.BooleanField(default=False, verbose_name='buzz'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='code',
            field=models.TextField(verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='code_en',
            field=models.TextField(null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='code_he',
            field=models.TextField(null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='testyourself',
            name='title_he',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='age_categories',
            field=models.CharField(choices=[('default', 'Default'), ('children', 'Children'), ('young', 'Young'), ('adults', 'Adults')], default='default', max_length=25, verbose_name='age categories'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='body_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='body_he',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='buzz',
            field=models.BooleanField(default=False, verbose_name='buzz'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='title_he',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=225, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_time_visit',
            field=models.DateTimeField(verbose_name='last_time_visit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=225, verbose_name='name'),
        ),
    ]
