# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbuzz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testyourself',
            name='post_ptr',
        ),
        migrations.DeleteModel(
            name='TestYourself',
        ),
    ]
