# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbuzz', '0002_auto_20161021_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='tag')),
                ('name_he', models.CharField(max_length=255, null=True, unique=True, verbose_name='tag')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='תגים', to='whatsbuzz.Tags'),
        ),
    ]
