# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbuzz', '0002_facebookuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookuser',
            name='first_name_en',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='first_name_he',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='last_name_en',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='last_name_he',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_he',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
