# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbuzz', '0002_auto_20161016_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=225, verbose_name='email'),
        ),
    ]
