# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbuzz', '0003_trend_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookusername',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=225, verbose_name='text align'),
        ),
        migrations.AlterField(
            model_name='facebookusername',
            name='username',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='empty', max_length=255, verbose_name='username'),
        ),
    ]
