# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbuzz', '0004_auto_20161112_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookgame',
            name='type',
            field=models.CharField(default='Facebook', editable=False, max_length=100, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='trend',
            name='type',
            field=models.CharField(default='Trend', editable=False, max_length=100, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='תגיות', to='whatsbuzz.Tags'),
        ),
    ]
