# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbuzz', '0004_auto_20161112_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='תגיות', to='whatsbuzz.Tags'),
        ),
    ]
