# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbuzz', '0005_auto_20161119_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookgamesimage',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/', verbose_name='banner image'),
        ),
    ]
