# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsbuzz', '0006_auto_20161203_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=255, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='tag'),
        ),
    ]
