sudo: required

language: python
python:
  - 3.5
  - 2.7

services:
  - postgresql

before_install:
  # Install nodejs for npm packages.
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
    sudo apt-get update
    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -;
    sudo apt-get install -y nodejs;
    fi

install:
  # Install code sniffer.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then
    pip install pycodestyle;
    pip install --upgrade pycodestyle;
    source ~/.bash_profile;
    source ~/.bashrc;
    fi

  # Install Angular CLI
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
    npm install -g angular-cli;
    cd client;
    npm install --no-optional;
    cd ..;
    fi

script:
  # Run code sniffer on the server directory.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then
    pycodestyle --show-source --max-line-length=119 --exclude=server/whatsbuzz/migrations --show-pep8 server;
    fi

  # Run e2e tests on the client directory.
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
    cd client;
    ng serve& ng e2e;
    fi
