# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamesImagesFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('post_type', models.CharField(choices=[('FG', 'משחקי פייסבוק'), ('TY', 'בחן את עצמך')], default='FG', max_length=2)),
                ('image_banner', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('buzz', models.BooleanField()),
                ('age_categories', models.CharField(choices=[('D', 'ברירת מחדל'), ('C', 'ילדים'), ('Y', 'נוער'), ('A', 'מבוגרים')], default='D', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whats_buzz.Post')),
            ],
        ),
        migrations.CreateModel(
            name='UserNameFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_user_name', models.CharField(choices=[('empty', ''), ('first_name', 'First name ONLY'), ('last_name', 'Last name ONLY'), ('full_name', 'The full user name')], default='empty', max_length=255)),
                ('name_x', models.PositiveIntegerField()),
                ('name_y', models.PositiveIntegerField()),
                ('font_color', models.CharField(max_length=255)),
                ('font_size', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whats_buzz.Post')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileImageFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_x', models.PositiveIntegerField()),
                ('profile_image_y', models.PositiveIntegerField()),
                ('profile_width', models.PositiveIntegerField()),
                ('profile_height', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whats_buzz.Post')),
            ],
        ),
        migrations.AddField(
            model_name='gamesimagesfb',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whats_buzz.Post'),
        ),
    ]
