# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_buzz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernamefb',
            name='facebook_user_name',
            field=models.CharField(choices=[('empty', ''), ('first_name', 'שם פרטי'), ('last_name', 'שם משפחה'), ('full_name', 'שם פרטי ומשפחה')], default='empty', max_length=255),
        ),
    ]
