/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './footer.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './footer.component.scss.shim';
var renderType_FooterComponent_Host:import0.RenderComponentType = (null as any);
class _View_FooterComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FooterComponent_0_4:import3.FooterComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FooterComponent_Host0,renderType_FooterComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('wb-footer',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FooterComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FooterComponent_0_4 = new import3.FooterComponent();
    this._appEl_0.initComponent(this._FooterComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._FooterComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.FooterComponent) && (0 === requestNodeIndex))) { return this._FooterComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_FooterComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_FooterComponent_Host === (null as any))) { (renderType_FooterComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_FooterComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const FooterComponentNgFactory:import9.ComponentFactory<import3.FooterComponent> = new import9.ComponentFactory<import3.FooterComponent>('wb-footer',viewFactory_FooterComponent_Host0,import3.FooterComponent);
const styles_FooterComponent:any[] = [import10.styles];
var renderType_FooterComponent:import0.RenderComponentType = (null as any);
class _View_FooterComponent0 extends import1.AppView<import3.FooterComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FooterComponent0,renderType_FooterComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'footer',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','container');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'p',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      כל הזכויות שמורות whatsbuzz.co.il |\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'a',(null as any));
    this.renderer.setElementAttribute(this._el_6,'routerLink','/privacy-policy');
    this._text_7 = this.renderer.createText(this._el_6,'מדניות פרטיות',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_11 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._text_11
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_FooterComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.FooterComponent> {
  if ((renderType_FooterComponent === (null as any))) { (renderType_FooterComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_FooterComponent,{})); }
  return new _View_FooterComponent0(viewUtils,parentInjector,declarationEl);
}