/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['footer[_ngcontent-%COMP%] {\n  position:absolute;\n  bottom:0;\n  width: 100vw;\n  background: #042B3A;\n  color: #a7bac9;\n\n  p {\n    text-align: center;\n  }\n}'];