/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['nav[_ngcontent-%COMP%] {\n  background: linear-gradient(#4e69a2,#3c5998);\n  border-bottom: solid 2px #21366e;\n  color: #ffffff;\n\n  ul {\n    float: right;\n    font-size: 18px;\n    padding: 0;\n\n    li {\n      cursor: pointer;\n      padding: 3px;\n      margin: 5px;\n      float: left;\n\n      :hover {\n        background: rgba(35,53,92,.57);\n      }\n\n      a {\n        transition: all 350ms ease;\n        padding: 15px 10px;\n        line-height: 20px;\n        display: block;\n        border-radius: 4px;\n      }\n    }\n  }\n\n  img {\n    float: left;\n  }\n}'];