# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_buzz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernamefb',
            name='font_color',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernamefb',
            name='font_size',
            field=models.PositiveIntegerField(default=26),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='age_categories',
            field=models.CharField(choices=[('D', 'ברירת מחדל'), ('C', 'ילדים'), ('Y', 'נוער'), ('A', 'מבוגרים')], default='D', max_length=3),
        ),
    ]
