# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_buzz', '0002_auto_20160426_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernamefb',
            name='text_align',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center')], default='left', max_length=225),
        ),
    ]
