# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_buzz', '0002_auto_20160220_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_banner',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/'),
        ),
    ]
