# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_buzz', '0003_post_buzz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='buzz',
            field=models.BooleanField(),
        ),
    ]
