# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whats_buzz', '0005_auto_20160227_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Name_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_user_name', models.CharField(choices=[('empty', ''), ('first_name', 'First name ONLY'), ('last_name', 'Last name ONLY'), ('full_name', 'The full user name')], default='empty', max_length=255)),
                ('profile_image_x', models.PositiveIntegerField()),
                ('profile_image_y', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whats_buzz.Post')),
            ],
        ),
    ]
