# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whats_buzz', '0006_user_name_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileImageFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_x', models.PositiveIntegerField()),
                ('profile_image_y', models.PositiveIntegerField()),
                ('profile_width', models.PositiveIntegerField()),
                ('profile_height', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whats_buzz.Post')),
            ],
        ),
        migrations.RenameModel(
            old_name='User_Name_Game',
            new_name='UserNameFB',
        ),
    ]
