# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whats_buzz', '0007_auto_20160313_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernamefb',
            old_name='profile_image_x',
            new_name='name_x',
        ),
        migrations.RenameField(
            model_name='usernamefb',
            old_name='profile_image_y',
            new_name='name_y',
        ),
    ]
