# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whats_buzz', '0008_auto_20160313_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesImagesFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whats_buzz.Post')),
            ],
        ),
    ]
