# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whats_buzz', '0012_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age_categories',
            field=models.CharField(choices=[('C', 'ילדים'), ('Y', 'נוער'), ('A', 'מבוגרים')], default='C', max_length=3),
            preserve_default=False,
        ),
    ]
